---
- name: Prepare
  hosts: all
  vars:
    ansible_user: vagrant

- import_playbook: ../../../tests/molecule/common/set_local_package_cache.yml
# - import_playbook: ../../../tests/molecule/common/add_test_user.yml
