---
# tasks file for upgrade-packages

- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: true
    update_cache: true
    cache_valid_time: "{{ '1d' | community.general.to_seconds | int }}"
    lock_timeout: "{{ '15m' | community.general.to_seconds | int }}"
  when: ansible_os_family == "Debian"
