---
# tasks file for upgrade-packages

- include_role: name="../apt-wait-for-unlock"
  when: ansible_os_family == "Debian"

- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: "yes"
    update_cache: yes
    # 1 hour
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"