---
# tasks file for linux-timezone

- name: Make sure 'dbus' package is installed
  apt:
    name: dbus
    update_cache: true
    cache_valid_time: "{{ '1d' | community.general.to_seconds | int }}"
    lock_timeout: "{{ '15m' | community.general.to_seconds | int }}"
  become: true
  when: ansible_os_family == "Debian"


- name: Set timezone to {{ linux_timezone_name }}
  timezone:
    name: "{{ linux_timezone_name }}"
  become: true
