---

- name: Check if server type is correct
  assert:
    that:
      - ovpn_client_server_type is in ["purevpn", "chere"]

- name: Check if mandatory variables are defined (chere)
  assert:
    that:
      - ovpn_client_server is defined
      - ovpn_client_chere_ta_key is defined or ovpn_client_chere_ta_key_file is defined
      - ovpn_client_chere_client_cert is defined or ovpn_client_chere_client_cert_file is defined
      - ovpn_client_chere_client_key is defined or ovpn_client_chere_client_key_file is defined
  when: ovpn_client_server_type == "chere"

- name: Check if mandatory variables are defined (purevpn)
  assert:
    that:
      - ovpn_client_server is defined
      - ovpn_client_purevpn_user is defined
      - ovpn_client_purevpn_password is defined
  when: ovpn_client_server_type == "purevpn"

- name: Check if optional variables are defined
  assert:
    that:
      - ovpn_client_operator_key is defined
      - ovpn_client_keys_dir is defined
  when: ovpn_client_operator is defined

- name: Make sure systemd-resolved DNS stub is disabled
  include_role: name="{{ role_path }}/../linux-dns"

- name: Add Speedtest repository key
  apt_key:
    url: https://packagecloud.io/ookla/speedtest-cli/gpgkey
    state: present
  become: yes

- name: Add Speedtest repository
  apt_repository:
    repo: deb https://packagecloud.io/ookla/speedtest-cli/ubuntu/ {{ ansible_distribution_release }} main
    state: present
  become: yes

- name: Install apt packages
  apt:
    name: [
      "netfilter-persistent", "openvpn", "putty-tools", "speedtest",
      "python3-humanfriendly"
    ]
    update_cache: yes
    # 1 hour
    cache_valid_time: 3600
  become: yes

- name: Create OpenVPN client config
  include_tasks: "{{ ovpn_client_server_type }}_config.yml"

- name: Copy resolv.conf update script
  ansible.builtin.copy:
    src: update_resolve_conf.py
    dest: /etc/openvpn/client/update_resolve_conf.py
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Copy systemd-resolved restore script
  ansible.builtin.copy:
    src: restore_systemd_resolved_dns.py
    dest: /etc/openvpn/client/restore_systemd_resolved_dns.py
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Make sure client service override directory exists
  file:
    path: "/etc/systemd/system/openvpn-client@{{ ovpn_client_server_type }}.service.d"
    state: directory
    mode: 0755
    owner: root
    group: root
  become: true

- name: Create override file for client service
  copy:
    content: |
      # Generated by Ansible at {{ lookup('pipe', 'hostname -f') }}
      # Any changes made here will be overwritten
      [Service]
      ExecStartPre=/etc/openvpn/client/restore_systemd_resolved_dns.py
    dest: "/etc/systemd/system/openvpn-client@{{ ovpn_client_server_type }}.service.d/override.conf"
    mode: 0644
  become: true
  notify: Run daemon-reload for systemd

- name: Enable and start client service
  ansible.builtin.systemd:
    name: "openvpn-client@{{ ovpn_client_server_type }}.service"
    state: started
    enabled: yes
  become: yes

- import_tasks: vpn_operator_config.yml
  when: ovpn_client_operator is defined

- name: Copy 'purevpn_change_country.py' script
  copy:
    src: purevpn_change_country.py
    dest: /etc/openvpn/client/purevpn_change_country.py
    mode: 0755
  become: true
