---

- name: Restart 'openvpn-client@purevpn' service
  ansible.builtin.systemd:
    name: openvpn-client@purevpn.service
    state: restarted
  become: yes

- name: Run daemon-reload for systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes
