---
- name: Install packages
  hosts: all
  gather_facts: no
  tasks:

  - name: Make sure 'net-tools' package is installed
    apt:
      name: net-tools
      update_cache: yes
      # 1 hour
      cache_valid_time: 3600
    become: yes
    when: ansible_os_family == "Debian"

  - name: Make sure 'net-tools' package is installed
    package:
      name: net-tools
      state: present
    become: yes
    when: ansible_os_family == "RedHat"
