---

scenario:
  test_sequence:
    # - dependency
    # - lint
    # - cleanup
    - destroy
    # - syntax
    - create
    - prepare
    - converge
    # - idempotence
    # - side_effect
    # - verify
    # - cleanup
    - destroy
