require "yaml"

docker_mirrors = []
if File.file?("local-config.yml")
  local_config = YAML.load_file("local-config.yml")
  unless local_config.nil?
    docker_mirrors = local_config.fetch("docker_mirrors", docker_mirrors)
  end
end


Vagrant.configure("2") do |config|
  config.vm.box = "cheretbe/docker-tests"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
  end

  config.vm.synced_folder "../../../", "/ansible-playbooks"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/provision.yml"
    ansible.compatibility_mode = "2.0"
    ansible.extra_vars = {
      "ansible_python_interpreter": "/usr/bin/python3",
      "docker_ce_registry_mirrors": docker_mirrors
    }
  end
end
