---
- name: Verify
  hosts: all
  gather_facts: false

  tasks:
  - name: Populate service facts
    service_facts:

  - name: Verify if Nagios NRPE service is running
    assert:
      that:
        - ansible_facts.services["nagios-nrpe-server"].state == "running"