ansible_version = `ansible --version`

Vagrant.configure("2") do |config|
  config.vm.box = "cheretbe/win10ltsc2019_ru_64"
  config.winrm.username = "vagrant"
  config.winrm.password = "#{ENV['AO_DEFAULT_VAGRANT_PASSWORD']}"
  config.vm.boot_timeout = 900
  # config.vm.network "private_network", ip: "192.168.199.11", virtualbox__intnet: "vagrant-domain"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
    ansible.compatibility_mode = "2.0"
    ansible.extra_vars = {
      "ansible_winrm_scheme": "http",
      "win_scheduled_command_wrapper_password": "#{ENV['AO_DEFAULT_VAGRANT_PASSWORD']}",
      "win_scheduled_command": "& cmd.exe /c ver"
    }
  end
end