---
- name: Prepare
  hosts: all
  become: true
  # gather_facts: false

  tasks:
    - name: "Set local package cache"
      ansible.builtin.include_tasks: "../../../tests/helper_tasks/set_local_package_cache.yml"

    - name: "Add test user"
      ansible.builtin.include_tasks: "../../../tests/helper_tasks/add_test_user.yml"
