---

- hosts: all
  tasks:
    - include_role:
        name: backuppc-client
      when: ansible_system == "Linux"

    - include_role:
        name: win-backuppc-client
      when: ansible_system == "Win32NT"
