---
- name: Setup docker host
  hosts: all
  tasks:
    - name: Check if recommended variables are defined
      display_warning:
        msg: Consider setting 'docker_ce_users' variable
      when: docker_ce_users is not defined

    - name: Install and configure Docker
      ansible.builtin.include_role:
        name: docker-ce

    # # become + become_user combination fails without this package
    # - name: Install acl APT package
    #   ansible.builtin.apt:
    #     name: ["acl"]
    #     update_cache: false
    #   become: true

    # - name: Make sure shared docker configs directory exists
    #   ansible.builtin.file:
    #     path: /opt/docker-configs
    #     state: directory
    #     owner: "{{ docker_ce_users[0] }}"
    #     group: docker
    #     # 2 sets setgid bit
    #     mode: "02755"
    #   become: true

    - name: Checkout shared docker configs repository # noqa: latest[git]
      ansible.builtin.git:
        repo: https://github.com/cheretbe/docker-configs.git
        dest: /opt/docker-configs
      become: true
      # become_user: "{{ docker_ce_users[0] }}"
