---

- name: Install Docker
  hosts: all
  tasks:
    - name: Check if recommended variables are defined
      display_warning:
        msg: Consider setting 'docker_ce_users' variable
      when: docker_ce_users is not defined

    - name: Install and configure Docker
      ansible.builtin.include_role:
        name: docker-ce
