---

- hosts: all
  become: yes
  roles:
    - linux-utils
    - linux-dns
    - linux-locale
    - linux-mta
    - linux-timezone
    - linux-unattended-upgrades
  tasks:
    - include_role:
        name: smartmontools
      when: ansible_virtualization_role != "guest"