---

- name: Setup MOTD
  hosts: all
  tasks:

    - name: Remove executable permission from unnecessary scripts in /etc/update-motd.d/
      ansible.builtin.file:
        path: "/etc/update-motd.d/{{ _lm_update_motdd_file }}"
        state: file
        mode: u-x,g-x,o-x
      become: true
      loop_control:
        loop_var: _lm_update_motdd_file
      loop:
        - 10-help-text
        - 50-motd-news

    - name: Install python3-rich package and make sure update-notifier-common package is the latest version
      ansible.builtin.apt:
        name: ["python3-rich", "update-notifier-common"]
        state: latest
        update_cache: true
        cache_valid_time: "{{ '1d' | community.general.to_seconds | int }}"
        lock_timeout: "{{ '15m' | community.general.to_seconds | int }}"
      become: true

    - name: Add disable ESM marker file
      ansible.builtin.file:
        path: /var/lib/update-notifier/hide-esm-in-motd
        state: touch
        mode: "0644"
        access_time: preserve
        modification_time: preserve
      become: true
      register: __lm_esm_marker_file

    - name: Remove current updates message file
      ansible.builtin.file:
        path:  /var/lib/update-notifier/updates-available
        state: absent
      become: true
      when:  __lm_esm_marker_file.changed

    - name: Update repositories cache to regenerate updates message file
      ansible.builtin.apt:
        name: ["update-notifier-common"]
        state: latest
        update_cache: true
      become: true
      when:  __lm_esm_marker_file.changed

    - name: Create custom MOTD script
      ansible.builtin.template:
        src: templates/etc_update-motd.d_99_ansible_custom.j2
        dest: /etc/update-motd.d/99-ansible-custom
        owner: root
        group: root
        mode: '0755'
      become: true

    - name: Create custom MOTD
      ansible.builtin.copy:
        content: "{{ linux_motd_custom_message }}"
        dest: /etc/update-motd.d/ansible_custom_message.txt
        mode: 0440
      become: true
      when: linux_motd_custom_message is defined
