---

- hosts: all
  become: yes
  tasks:
    - include_role: name="{{ playbook_dir }}/ovpn-server"

    - name: Update facts to make ansible_tun0 variable available
      setup:

    - include_role: name="{{ playbook_dir }}/router"
