---

lint: |
    set -e
    ansible-lint --exclude molecule/

verifier:
  name: testinfra
  directory: ../../tests/
  options:
    v: true
    # s: true
    rsync-address: 127.0.0.1

scenario:
  test_sequence:
    # - dependency
    - lint
    # - cleanup
    - destroy
    # - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    # - cleanup
    - destroy
