---
- name: Converge
  hosts: ubuntu-bionic, ubuntu-focal
  vars:
    # https://github.com/cheretbe/notes/blob/master/ansible.md#environment-variables
    ansible_user: "{{ lookup('env','MOLECULE_USER_NAME') | default('ansible-test', true) }}"
    backuppc_github_oauth_token: "{{ lookup('env','AO_GITHUB_OAUTH_TOKEN') }}"
    backuppc_server_rsync_bpc_version: latest
    rsync_bpc_installed_version: "0.0"
    install_rsync_bpc: false
    backuppc_service_is_present: false

  tasks:
    - name: Set GitHub OAuth header
      set_fact:
        backuppc_github_oauth_header: {Authorization: "token {{ backuppc_github_oauth_token }}"}
      when: backuppc_github_oauth_token != ""

    - name: Include tasks from install_rsync_bpc.yml
      import_tasks: ../../tasks/install_rsync_bpc.yml
