---
all:
  vars:
    ansible_user: vagrant
  hosts:
    ubuntu-bionic:
      ansible_host: 172.24.0.11
    ubuntu-xenial:
      ansible_host: 172.24.0.12
    centos-7:
      ansible_host: 172.24.0.13
