---
# handlers file for linux-mta

- name: Restart 'postfix' service
  ansible.builtin.service:
    name: postfix
    state: restarted
    enabled: true
  become: true

- name: Re-initialize aliases database
  ansible.builtin.command: /usr/bin/newaliases
  # This is to silence linter warning. Handler is always called on change
  changed_when: true
  become: true
