---
- name: Set user name
  set_fact:
    win_settings_user_name: "{{ win_settings_user_name | default(ansible_user) }}"

  # HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList
  # (or see what Ansible offers in user info)
- name: Set user profile path
  set_fact:
    # Windows doesn't have an env variable for profiles directory, so here we
    # are getting "all users" profile path and replacing hard-coded "Public"
    # part with our user name
    win_settings_user_profile: "{{ ansible_env.PUBLIC | replace ('Public', win_settings_user_name) }}"

- debug:
    var: win_settings_user_profile

# - name: Create a file from a Jinja2 template
#   ansible.windows.win_template:
#     src: /mytemplates/file.conf.j2
#     dest: C:\Temp\file.conf