---
- name: Get Total Commander settings info
  ansible.windows.win_stat:
    path: "{{ ansible_env.APPDATA }}\\GHISLER\\wincmd.ini"
  register: win_settings_wincmd_ini

- name: Install Chocolatey packages
  win_chocolatey:
    name: "{{ item.name }}"
    state: present
    package_params: "{{ item.params | default('') }}"
    ignore_checksums: "{{ item.ignore_checksums | default(false) }}"
  loop:
    - {"name": "7zip", ignore_checksums: yes}
    - {"name": "winrar", ignore_checksums: yes}
    - {"name": "xnview", ignore_checksums: yes}
    - {"name": "git", params: "/GitAndUnixToolsOnPath /NoShellIntegration", ignore_checksums: yes}
    - {"name": "totalcommander", ignore_checksums: yes}
    - {"name": "googlechrome", ignore_checksums: yes}
    - {"name": "firefox", ignore_checksums: yes}

- name: Remove default Total Commander settings file
  ansible.windows.win_file:
    path: "{{ ansible_env.APPDATA }}\\GHISLER\\wincmd.ini"
    state: absent
  when: not win_settings_wincmd_ini.stat.exists

- name: Add 'uBlock Origin' extension to Google Chrome
  win_regedit:
    path: HKLM:\SOFTWARE\WOW6432Node\Google\Chrome\Extensions\cjpalhdlnbpafiamejdnhcphjbkeiagm
    name: update_url
    data: https://clients2.google.com/service/update2/crx

- name: Make sure Mozilla Firefox's distribution directory exists
  ansible.windows.win_file:
    path: "{{ ansible_env.ProgramFiles }}\\Mozilla Firefox\\distribution"
    state: directory

- name: Add 'uBlock Origin' extension to Mozila Firefox
  ansible.windows.win_copy:
    src: firefox_policies.json
    dest: "{{ ansible_env.ProgramFiles }}\\Mozilla Firefox\\distribution\\policies.json"
    backup: yes

- name: Get 'All Users' profile path
  ansible.windows.win_reg_stat:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList
    name: Public
  register: win_utils_all_users_profile

- name: Create Total Commander shortcut on the desktop for all users
  community.windows.win_shortcut:
    src: "C:\\Program Files (x86)\\totalcmd\\TOTALCMD64.EXE"
    dest: "{{ win_utils_all_users_profile.value }}\\Desktop\\Total Commander.lnk"
