- name: Restart 'openvpn-server@server' service
  ansible.builtin.systemd:
    name: "openvpn-server@server.service"
    state: restarted
  become: yes

- name: Restart 'named' service
  ansible.builtin.systemd:
    name: named
    state: restarted
  become: yes
