---
# tasks file for nagios-client

- name: Configure smartmontools when not running in a VM
  include_role:
    name: "{{ role_path }}/../smartmontools"
  when: ansible_virtualization_role != "guest"

- name: Install prerequisite packages
  ansible.builtin.apt:
    name: [
      "acl", "git", "libconfig-json-perl", "smartmontools", "monitoring-plugins",
      "nagios-nrpe-server"
    ]
    state: present
    update_cache: true
    cache_valid_time: "{{ '1d' | community.general.to_seconds | int }}"
    lock_timeout: "{{ '15m' | community.general.to_seconds | int }}"
  become: true

- name: Checkout custom plugins git repo
  git:
    repo: https://github.com/cheretbe/nagios-plugins.git
    # 401 - Git checkouts must contain explicit version
    version: HEAD # noqa 401
    dest: /var/lib/nagios/nagios-plugins
  become_user: nagios
  become: true

- name: "Add sudoers file to enable passwordless sudo commands for nagios user"
  template:
    src: etc_sudoers_d_nagios.j2
    dest: /etc/sudoers.d/ansible_nagios
    owner: root
    group: root
    mode: 0440
    validate: "/usr/sbin/visudo -cf %s"
  become: true

- name: "Add custom NRPE settings template"
  template:
    src: etc_nagios_nrpe_d_ansible_custom_cfg.j2
    dest: /etc/nagios/nrpe.d/ansible_custom.cfg
    owner: root
    group: root
    mode: 0644
    # Don't replace file if it already exists
    force: no
  become: true
  notify: Restart Nagios NRPE service
