---
- name: Converge
  hosts: ubuntu-bionic, ubuntu-focal
  vars:
    # https://github.com/cheretbe/notes/blob/master/ansible.md#environment-variables
    ansible_user: "{{ lookup('env','MOLECULE_USER_NAME') | default('ansible-test', true) }}"
  tasks:
    - name: "Include backuppc-server"
      include_role:
        name: "backuppc-server"
