---
- name: Converge
  hosts: all
  vars:
    ansible_user: ansible
    # backuppc_server_version: 4.3.0
  tasks:
    - name: "Include backuppc-server"
      include_role:
        name: "backuppc-server"
