---
- name: Converge
  hosts: all
  vars:
    ansible_user: ansible
    # https://nikhilism.com/post/2016/understanding-ansible-jinja2-default-filter/
    backuppc_server_version: "{{ lookup('env','TEST_BACKUPPC_VERSION') | default('latest', true) }}"
    backuppc_server_backuppc_xs_version: "{{ lookup('env','TEST_BACKUPPC_XS_VERSION') | default('latest', true) }}"
    backuppc_server_rsync_bpc_version: "{{ lookup('env','TEST_BACKUPPC_RSYNC_BPC_VERSION') | default('latest', true) }}"
  tasks:
    - name: "Include backuppc-server"
      include_role:
        name: "backuppc-server"
