---

scenario:
  test_sequence:
    # - dependency
    # - lint
    # - cleanup
    - destroy
    # - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    # - cleanup
    - destroy

verifier:
  name: testinfra
  directory: ../../tests/
  options:
    v: true
    # s: true
    hosts: ubuntu-bionic,ubuntu-focal
    m: ver_rsync_bpc
    # rsync_bpc_version: "3.0.9.13"
