-  import_playbook: ../common/playbooks/prepare.yml

- name: Set up test environment
  hosts: all

  tasks:
    - name: Make sure /root/wrong_link exists
      file:
        state: directory
        path: /root/wrong_link

    - name: Create /var/lib/backuppc symbolic link
      file:
        src: /root/wrong_link
        dest: /var/lib/backuppc
        state: link