- name: "Remove user '{{ backuppc_server_user_name }}'"
  user:
    name: "{{ backuppc_server_user_name }}"
    state: absent
  become: yes

- name: Make sure '/var/lib/backuppc' does not exist
  file:
    state: absent
    path: /var/lib/backuppc
  become: yes

- name: Make sure '/test/backuppc_test_dir' exists
  file:
    state: directory
    owner: root
    group: root
    mode: 0777
    path: /test/backuppc_test_dir
  become: yes
