---
- name: Verify
  hosts: ubuntu-bionic, ubuntu-focal
  vars:
    # https://github.com/cheretbe/notes/blob/master/ansible.md#environment-variables
    test_converge_ansible_user: "{{ lookup('env','MOLECULE_USER_NAME') | default('ansible-test', true) }}"
    backuppc_server_user_name: backuppc-server

  tasks:
    # ==========================================================================
    - name: Include tasks from setup_user.yml (default settings)
      include_tasks: ../../tasks/setup_user.yml
      vars:
        ansible_user: "{{ test_converge_ansible_user }}"

    - name: "Verify data directory settings"
      include_tasks: "../../../tests/helper_tasks/run_test_infra.yml"
      vars:
        test_dir: "{{ playbook_dir }}/../../tests"
        # test_extra_params: "--user-name backuppc-test-user"

    # # ==========================================================================
    # - name: "Include linux-unattended-upgrades (automatic reboot)"
    #   include_role:
    #     name: "linux-unattended-upgrades"
    #   vars:
    #     ansible_user: "{{ test_converge_ansible_user }}"
    #     unattended_automatic_reboot: true

    # - name: "Verify unattended upgrades settings"
    #   include_tasks: "../../../tests/helper_tasks/run_test_infra.yml"
    #   vars:
    #     test_dir: "{{ playbook_dir }}/../../tests"
    #     test_extra_params: "--autoreboot --reboot-time=02:00"
