---
- name: Verify
  hosts: all
  tasks:

  - name: Get test date representation
    command: su - ansible-test -c "date -d'2019-11-09T11:36:14+00:00' +'%A'"
    register: date_output
    # become: true
    changed_when: false
    # This is to suppress a warning: Consider using 'become', 'become_method',
    # and 'become_user' rather than running su
    # Using become_user leads to LANG parameter to not set correctly from
    # system default locale config. May be this is because of AcceptEnv SSH
    # directive. Or maybe not. Anyway, we just need a quick confirmation
    # of default locale being set correctly and su works ok.
    args:
      warn: false

  - name: Change me
    assert:
      that: date_output.stdout_lines[0] == "sábado"
