---
# tasks file for smartmontools

- name: Check if running on a physical machine
  ansible.builtin.fail:
    msg: "Will not install in a VM or a container. Use 'smartmontools_force_vm' parameter to override"
  when:
    - ansible_facts['virtualization_role'] == "guest"
    - not (smartmontools_force_vm | bool)

# smartmontools package depends on postfix package. We use MTA installation
# role to make sure that postfix is configured properly.
- name: Include linux-mta role
  ansible.builtin.include_role:
    name: linux-mta

- name: Install smartmontools package
  ansible.builtin.apt:
    name: "smartmontools"
    update_cache: true
    cache_valid_time: "{{ '1d' | community.general.to_seconds | int }}"
    lock_timeout: "{{ '15m' | community.general.to_seconds | int }}"
  become: true

- name: "Write custom smartd config"
  ansible.builtin.template:
    src: etc_smartd.conf.j2
    dest: /etc/smartd.conf
    owner: root
    group: root
    mode: "0644"
    backup: true
  become: true
