---
- name: Verify
  hosts: all
  tasks:

    - name: Verify auto-reboot settings
      include_role:
        name: "../tests/verify_auto_reboot_settings"
      vars:
        molecule_test_auto_reboot: true

    - name: Verify reboot time config
      include_role:
        name: "../tests/verify_auto_reboot_time"
      vars:
        molecule_test_cron_reboot_line: >-
          00 02 * * * root systemd-cat -t ansible-unattended-upgrades
          /opt/ansible-scripts/unattended_upgrades/check_if_reboot_is_needed.py
        molecule_test_reboot_line: >-
          Unattended-Upgrade::Automatic-Reboot-Time "02:00";
