---
- name: Prepare
  hosts: ubuntu-bionic, ubuntu-focal
  become: true
  # gather_facts: false
  vars:
    backuppc_server_user_name: backuppc-server

  tasks:
    - name: Set local package cache
      include_tasks: "../../../tests/helper_tasks/set_local_package_cache.yml"

    - name: Add test user
      include_tasks: "../../../tests/helper_tasks/add_test_user.yml"
      # vars:
      #   test_dir: "{{ playbook_dir }}/../../tests"

    - name: Install packages
      apt:
        name: ["apache2", "apache2-utils", "python3-passlib"]
        update_cache: yes
        # 1 hour
        cache_valid_time: 3600

    - name: Create test file '/etc/apache2/conf-available/backuppc.conf'
      get_url:
        url: https://github.com/backuppc/backuppc/raw/master/httpd/src/BackupPC.conf
        dest: /etc/apache2/conf-available/backuppc.conf
      become: yes

    - name: Make a copy of Apache config template
      copy:
        src: "{{ lookup('env','MOLECULE_PROJECT_DIRECTORY') }}/templates/var_www_html_index.html.j2"
        dest: "{{ lookup('env','MOLECULE_PROJECT_DIRECTORY') }}/molecule/apache/templates/var_www_html_index.html.j2"
      delegate_to: localhost
      become: no

    - name: Create '/var/www/cgi-bin/BackupPC' directory
      file:
        path: /var/www/cgi-bin/BackupPC
        state: directory
        mode: '0755'

    - name: Create test file '/var/www/cgi-bin/BackupPC/BackupPC_Admin'
      copy:
        dest: /var/www/cgi-bin/BackupPC/BackupPC_Admin
        content: ""
      become: yes

    - name: Create '/etc/BackupPC' directory
      file:
        path: /etc/BackupPC
        state: directory
        mode: '0755'

    - name: Setup user
      include_tasks: ../../tasks/setup_user.yml
