---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-focal
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
    privileged: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  env:
  #   ANSIBLE_LIBRARY: /ansible-playbooks/library
    ANSIBLE_LIBRARY: ${MOLECULE_PROJECT_DIRECTORY}../../library
verifier:
  name: ansible
