---

- block:
    - include_role: name="../apt-wait-for-unlock"

    - name: Make sure apt 'sendmail' package is not installed
      apt:
        name: sendmail
        state: absent
        purge: yes

    # We select "No configuration" option to prevent configuration being
    # overwritten on possible future dpkg-reconfigure calls
    # Use 'debconf-show postfix' or 'debconf-get-selections | grep postfix' to view
    # all available questions
    - name: Configure apt 'postfix' package (No configuration)
      debconf:
        name: postfix
        question: "postfix/main_mailer_type"
        value: "No configuration"
        vtype: select
      become: yes

    - name: Install apt 'postfix' package
      apt:
        name: postfix
        update_cache: yes
        # 1 hour
        cache_valid_time: 3600
      become: yes

  when: ansible_os_family == "Debian"

- block:
    - name: Make sure yum 'sendmail' package is not installed
      yum:
        name: sendmail
        state: absent
      become: yes

    - name: Install yum 'postfix' package
      yum:
        name: postfix
        state: present
      become: yes

  when: ansible_os_family == "RedHat"

- name: Update postfix config file
  template:
    src: etc_postfix_main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  notify: Restart 'postfix' service

- name: Update system aliases table
  template:
    src: etc_aliases.j2
    dest: /etc/aliases
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes
  notify: Re-initialize aliases database
