---
# tasks file for linux-utils

- include_role: name="../apt-wait-for-unlock"
  when: ansible_os_family == "Debian"

- name: Install APT packages
  apt:
    name:
      - mc
      - htop
      - net-tools
      - dnsutils
      - mtr-tiny
      - ncdu
      - wget
      - git
      - nano
      - traceroute
      - colordiff
      - jq
      - pv
    update_cache: yes
    # 1 hour
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install YUM packages
  yum:
    name:
      - mc
      - htop
      - net-tools
      - bind-utils
      - mtr
      - ncdu
      - wget
      - git
      - nano
      - traceroute
      - colordiff
      - jq
      - pv
    state: present
  when: ansible_os_family == "RedHat"
