---
# tasks file for linux-utils

- name: Make sure dpkg frontend lock is released
  include_role: name="{{ role_path }}/../apt-wait-for-unlock"
  when: ansible_os_family == "Debian"

- name: Install APT packages
  apt:
    name:
      - mc
      - htop
      - net-tools
      - dnsutils
      - mtr-tiny
      - ncdu
      - wget
      - git
      - nano
      - traceroute
      - colordiff
      - jq
      - pv
    update_cache: yes
    # 1 hour
    cache_valid_time: 3600
  become: yes
  when: ansible_os_family == "Debian"

- name: Make sure EPEL repo is enabled
  yum:
    name: epel-release
    state: present
  become: yes
  when: ansible_os_family == "RedHat"

- name: Install YUM packages
  yum:
    name:
      - mc
      - htop
      - net-tools
      - bind-utils
      - mtr
      - ncdu
      - wget
      - git
      - nano
      - traceroute
      - colordiff
      - jq
      - pv
    state: present
  become: yes
  when: ansible_os_family == "RedHat"
