---
# tasks file for linux-utils

- name: Install APT packages
  apt: 
    name:
      - mc
      - htop
      - net-tools
      - dnsutils
      - mtr-tiny
      - ncdu
      - wget
      - git
      - nano
      - traceroute
      - colordiff
      - net-tools
      - jq
      - pv
    update_cache: yes
    # Fix for warning message "Could not find aptitude. Using apt-get instead"
    force_apt_get: yes
  when: ansible_os_family == "Debian"

- name: Install YUM packages
  yum:
    name:
      - mc
      - htop
      - net-tools
      - bind-utils
      - mtr
      - ncdu
      - wget
      - git
      - nano
      - traceroute
      - colordiff
      - net-tools
      - jq
      - pv
    state: present
  when: ansible_os_family == "RedHat"