---
- name: Add apache require directive
  lineinfile:
    dest: /etc/apache2/conf-available/backuppc.conf
    line: "    {{ backuppc_server_apache_require }}"
    insertafter: "^    [Rr]equire local"
    state: present
  become: yes
  notify: Restart Apache

- name: "Replace default apache user with {{ backuppc_server_user_name }}"
  lineinfile:
    path: /etc/apache2/envvars
    regexp: "export APACHE_RUN_USER=www-data"
    line: "export APACHE_RUN_USER={{ backuppc_server_user_name }}"
    backup: yes
  become: yes
  notify: Restart Apache

- name: "Replace default apache group with {{ backuppc_server_user_name }}"
  lineinfile:
    path: /etc/apache2/envvars
    regexp: "export APACHE_RUN_GROUP=www-data"
    line: "export APACHE_RUN_GROUP={{ backuppc_server_user_name }}"
  become: yes
  notify: Restart Apache

- name: Set custom /var/www/html/index.html
  template:
    src: var_www_html_index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: yes

- name: Enable apache module cgid
  apache2_module:
    name: cgid
    state: present
  become: yes
  notify: Restart Apache

- name: Enable backuppc apache config
  command: a2enconf backuppc
  args:
    creates: /etc/apache2/conf-enabled/backuppc.conf
  become: yes
  notify: Restart Apache

- name: Update permissions on /var/www/cgi-bin/BackupPC/BackupPC_Admin
  file:
    path: /var/www/cgi-bin/BackupPC/BackupPC_Admin
    mode: "u-s"
  become: yes

- name: Add passwords to /etc/BackupPC/BackupPC.users
  htpasswd:
    path: /etc/BackupPC/BackupPC.users
    name: "{{ item.user_name }}"
    password: "{{ item.password }}"
    owner: "{{ backuppc_server_user_name }}"
    group: "{{ backuppc_server_user_name }}"
    mode: 0640
  with_items: "{{ backuppc_server_www_users }}"
  become: yes
  no_log: yes
