- name: Wait for dpkg frontend to unlock
  include_role: name="../apt-wait-for-unlock"

- name: Install packages
  apt:
    name:  ["apache2", "apache2-utils", "libapache2-mod-perl2", "smbclient",
            "rrdtool", "libarchive-zip-perl", "libfile-listing-perl",
            "libxml-rss-perl", "libcgi-session-perl", "make", "gcc", "par2",
            "libacl1", "libacl1-dev",
            # this is for Ansible's htpasswd module
            "python3-passlib"]
    update_cache: yes
    # 1 hour
    cache_valid_time: 3600
  become: yes
