---
- name: Get latest BackupPC-XS version
  uri:
    url: https://api.github.com/repos/backuppc/backuppc-xs/releases/latest
    return_content: yes
  register: backuppc_xc_latest_release
  when: backuppc_server_backuppc_xs_version == "latest"

- name: Update BackupPC-XS version variable
  set_fact:
    backuppc_server_backuppc_xs_version: "{{ (backuppc_xc_latest_release.content | from_json).tag_name }}"
  when: backuppc_server_backuppc_xs_version == "latest"

- name: Try to get installed BackupPC-XS version
  command: perl -e 'use lib "/usr/local/BackupPC/lib"; use BackupPC::XS; print $BackupPC::XS::VERSION'
  # shell: perl -e 'print "0.58"'
  failed_when: false
  changed_when: false
  register: backuppc_xc_status

- name: Set BackupPC-XS version if installed
  set_fact:
    backuppc_xc_installed_version: "{{ backuppc_xc_status.stdout_lines[0] }}"
  when: backuppc_xc_status.rc == 0

- name: >-
    Check if installed BackupPC-XS version {{ backuppc_xc_installed_version }}
    needs upgrade to {{ backuppc_server_backuppc_xs_version }}"
  set_fact:
    install_backuppc_xc: true
  when: "backuppc_xc_installed_version is version(backuppc_server_backuppc_xs_version, '<')"

# - debug:
#     var: install_backuppc_xc

- block:
  - name: Get temporary directory for building
    tempfile:
      state: directory
      prefix: 'backuppc-'
    register: backuppc_build_dir
    when: backuppc_build_dir is not defined

  - name: "Download BackupPC-XS {{ backuppc_server_backuppc_xs_version }}"
    get_url:
      url: "https://github.com/backuppc/backuppc-xs/releases/download/\
             {{ backuppc_server_backuppc_xs_version }}/\
             BackupPC-XS-{{ backuppc_server_backuppc_xs_version }}.tar.gz"
      dest: "{{ backuppc_build_dir.path }}"

  - name: "Extract BackupPC-XS-{{ backuppc_server_backuppc_xs_version }}.tar.gz"
    unarchive:
      src: "{{ backuppc_build_dir.path }}/BackupPC-XS-{{ backuppc_server_backuppc_xs_version }}.tar.gz"
      dest: "{{ backuppc_build_dir.path }}"
      remote_src: yes

  - name: Stop 'backuppc' service
    systemd:
      name: backuppc
      state: stopped
    become: true
    when: backuppc_service_is_present

  - debug:
      var: backuppc_build_dir.path

  - name: "Build and install BackupPC-XS"
    shell: "perl Makefile.PL && make && make test && make install"
    args:
      chdir: "{{ backuppc_build_dir.path }}/BackupPC-XS-{{ backuppc_server_backuppc_xs_version }}"
    become: true
  when: install_backuppc_xc
