---
# tasks file for backuppc-server

- name: Check distribution
  fail:
    msg: "Only Ubuntu 18.04 and 20.04 are supported"
  when: (ansible_distribution != "Ubuntu") or
        (ansible_distribution_version not in ["18.04", "20.04"])

- name: Wait for dpkg frontend to unlock
  include_role: name="../apt-wait-for-unlock"

- name: Install dependencies
  apt:
    name:  ["apache2", "apache2-utils", "libapache2-mod-perl2", "smbclient",
            "rrdtool", "libarchive-zip-perl", "libfile-listing-perl",
            "libxml-rss-perl", "libcgi-session-perl", "make", "gcc", "par2",
            "libacl1", "libacl1-dev",
            # this is for Ansible's htpasswd module
            "python3-passlib"]
    update_cache: yes
    # 1 hour
    cache_valid_time: 3600
  become: yes

- name: Setup server user
  include_tasks: setup_user.yml

- name: Populate service facts
  service_facts:
  become: True

- name: Check if 'backuppc' service is present
  set_fact:
    backuppc_service_is_present: "{{ True if ('backuppc.service' in ansible_facts.services) else False }}"

- name: Install BackupPC-XS
  include_tasks: install_backuppc_xs.yml

- name: Install Rsync-bpc
  include_tasks: install_rsync_bpc.yml

- name: Install BackupPC
  include_tasks: install_backuppc.yml

- name: "Remove temporary build directory"
  file:
    state: absent
    path: "{{ backuppc_build_dir.path }}"
  become: true
  when: backuppc_build_dir.path is defined

- block:
  - name: Debug
    debug:
      msg: End playbook
  - meta: end_play

# ------------------------------------------------------

- name: Set group name in /etc/systemd/system/backuppc.service
  ini_file:
    path: /etc/systemd/system/backuppc.service
    section: Service
    option: Group
    value: "{{ backuppc_server_user_name }}"
    no_extra_spaces: true
  become: true

- name: Add apache allow directive
  lineinfile:
    dest: /etc/apache2/conf-available/backuppc.conf
    regex: "[Aa]llow from 127\\.0\\.0\\.1"
    line: "{{ backuppc_server_apache_allow }}"
    insertafter: "[Dd]eny from all"
  become: true
  notify: Restart Apache

- name: "Replace default apache user with {{ backuppc_server_user_name }}"
  lineinfile:
    path: /etc/apache2/envvars
    regexp: "export APACHE_RUN_USER=www-data"
    line: "export APACHE_RUN_USER={{ backuppc_server_user_name }}"
    backup: true
  become: true
  notify: Restart Apache

- name: "Replace default apache group with {{ backuppc_server_user_name }}"
  lineinfile:
    path: /etc/apache2/envvars
    regexp: "export APACHE_RUN_GROUP=www-data"
    line: "export APACHE_RUN_GROUP={{ backuppc_server_user_name }}"
  become: true
  notify: Restart Apache

- name: Set custom /var/www/html/index.html
  template:
    src: var_www_html_index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
    backup: true
  become: true

- name: Enable apache module cgid
  apache2_module:
    name: cgid
    state: present
  become: true
  notify: Restart Apache

- name: Enable backuppc apache config
  command: a2enconf backuppc
  args:
    creates: /etc/apache2/conf-enabled/backuppc.conf
  become: true
  notify: Restart Apache

- name: Update permissions on /var/www/cgi-bin/BackupPC/BackupPC_Admin
  file:
    path: /var/www/cgi-bin/BackupPC/BackupPC_Admin
    mode: "u-s"
  become: true

- name: Add passwords to /etc/BackupPC/BackupPC.users
  htpasswd:
    path: /etc/BackupPC/BackupPC.users
    name: "{{ item.user_name }}"
    password: "{{ item.password }}"
    owner: "{{ backuppc_server_user_name }}"
    group: "{{ backuppc_server_user_name }}"
    mode: 0640
  with_items: "{{ backuppc_server_www_users }}"
  become: true
  no_log: true

- name: Update ownership on /etc/BackupPC
  file:
    dest: /etc/BackupPC
    owner: "{{ backuppc_server_user_name }}"
    group: "{{ backuppc_server_user_name }}"
    recurse: true
  become: true

- name: Update CgiAdminUsers parameter in /etc/BackupPC/config.pl
  lineinfile:
    path: /etc/BackupPC/config.pl
    regexp: "\\$Conf\\{CgiAdminUsers\\}[ ]*=[ ]*'';"
    line: "$Conf{CgiAdminUsers} = '{{ backuppc_server_user_name }}';"
    backup: true
  become: true

- name: Start 'backuppc' service
  systemd:
    name: backuppc
    state: started
    enabled: true
    daemon_reload: true
  become: true
