---
- name: "Setup custom data directory"
  block:
    - name: "Make sure custom data directory exists"
      file:
        path: "{{ backuppc_server_custom_data_dir }}"
        state: directory

    - name: "Get /var/lib/backuppc stats"
      stat:
        path: /var/lib/backuppc
      register: home_dir_info

    - name: "Check if /var/lib/backuppc is a valid symlink"
      assert:
        that:
          - home_dir_info.stat.islnk
          - home_dir_info.stat.lnk_source == backuppc_server_custom_data_dir
        msg: >-
          /var/lib/backuppc exists and is not linked to {{ backuppc_server_custom_data_dir }}.
          Please fix the symlink before continuing.
      when: home_dir_info.stat.exists

    - name: Create /var/lib/backuppc symbolic link
      file:
        src: "{{ backuppc_server_custom_data_dir }}"
        dest: /var/lib/backuppc
        state: link
  when: backuppc_server_custom_data_dir|length > 0
  become: true
