---
# tasks file for linux-unattended-upgrades

- name: Create custom unattended upgrades configuration
  template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/90-ansible-unattended-upgrades
    owner: root
    group: root
    mode: 064