---
# tasks file for linux-unattended-upgrades

- name: Create custom unattended upgrades configuration (Ubuntu)
  template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/90-ansible-unattended-upgrades
    owner: root
    group: root
    mode: 0644
  become: yes
  when: ansible_os_family == "Debian"

- name: Setup unattended upgrades (CentOS)
  include_tasks: unattended_upgrades_centos.yml
  when: ansible_os_family == "RedHat"
