---
- name: Wait for dpkg frontend to unlock
  include_role: name="../apt-wait-for-unlock"

- name: Install apt 'unattended-upgrades' package
  apt:
    name: unattended-upgrades
    update_cache: yes
    # 1 hour
    cache_valid_time: 3600
  become: yes

- name: Create custom unattended upgrades configuration file
  template:
    src: etc_apt_apt.conf.d_90-ansible-unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/90-ansible-unattended-upgrades
    owner: root
    group: root
    mode: 0644
  become: yes
