---
# tasks file for linux-dns

- name: Populate service facts
  service_facts:
  become: true

- name: Check if systemd-resolved service is present
  set_fact:
    linux_dns_has_resolved: true
  when: "'systemd-resolved.service' in ansible_facts.services"

- name: Check if systemd-resolved service is disabled
  set_fact:
    linux_dns_has_resolved: false
  when:
    - linux_dns_has_resolved | bool
    - ansible_facts.services["systemd-resolved.service"]["status"] != "enabled"

- block:
    - name: Get systemd version info
      # Disable 303: systemctl used in place of systemd module
      # systemd module doesn't expose version info
      command: systemctl --version  # noqa command-instead-of-module
      register: linux_dns_systemd_info
      changed_when: false

      # The first line should contain version info like this:
      # systemd 237
    - name: Get systemd version
      set_fact:
        linux_dns_systemd_version: "{{ linux_dns_systemd_info.stdout_lines[0].split(' ')[-1] }}"

    # As of systemd 232 DNS stub listener can be disabled
    # https://www.freedesktop.org/software/systemd/man/resolved.conf.html
    - name: "Check if resolved DNS stub could be disabled"
      set_fact:
        linux_dns_disable_stub: true
        when: "linux_dns_systemd_version|int >= 232"

    - name: Make sure '/etc/systemd/resolved.conf.d' directory exists
      file:
        path: /etc/systemd/resolved.conf.d
        state: directory
        mode: 0755
        owner: root
        group: root
      become: true
      when: linux_dns_disable_stub | bool

    - name: Disable systemd-resolved DNS stub
      copy:
        content: |
          # Generated by Ansible at {{ lookup('pipe', 'hostname -f') }}
          # Any changes made here will be overwritten
          [Resolve]
          DNSStubListener=no
        dest: /etc/systemd/resolved.conf.d/10-disable-dns-stub.conf
        mode: 0644
      become: true
      when: linux_dns_disable_stub | bool
      notify: Restart systemd-resolved service

    - name: "Get '/etc/resolv.conf' info"
      stat:
        path: /etc/resolv.conf
      register: linux_dns_resolv_conf_info

    - name: "Update '/etc/resolv.conf' symlink"
      file:
        src: "/run/systemd/resolve/resolv.conf"
        dest: "/etc/resolv.conf"
        state: link
      become: true
      when: >-
        linux_dns_resolv_conf_info.stat.islnk
        and
        linux_dns_resolv_conf_info.stat.lnk_source == "/run/systemd/resolve/stub-resolv.conf"

  when: linux_dns_has_resolved | bool
