- name: Set up test environment
  hosts: all

  tasks:
    - name: Install dependencies
      apt:
        name:  ["curl", "net-tools", "jq"]
        update_cache: yes
      when: ansible_os_family == "Debian"