---
- name: Install Chocolatey packages
  win_chocolatey:
    name: "{{ item.name }}"
    state: present
    package_params: "{{ item.params | default('') }}"
  loop:
    - {"name": "7zip"}
    - {"name": "winrar"}
    - {"name": "xnview"}
    - {"name": "git", params: "/GitOnlyOnPath /NoShellIntegration"}
    - {"name": "totalcommander", params: "/DesktopIcon"}
    - {"name": "googlechrome"}
    - {"name": "firefox"}

- name: Add 'uBlock Origin' extension to Google Chrome
  win_regedit:
    path: HKLM:\SOFTWARE\WOW6432Node\Google\Chrome\Extensions\cjpalhdlnbpafiamejdnhcphjbkeiagm
    name: update_url
    data: https://clients2.google.com/service/update2/crx
