---
lint: |
  set -e
  ansible-lint --exclude molecule/default/verify.yml \
    --exclude molecule/changing_settings/verify.yml \
    --exclude molecule/apt_origins/verify.yml
  # flake8 --max-line-length 100

scenario:
  test_sequence:
    # - dependency
    - lint
    # - cleanup
    - destroy
    # - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    # - cleanup
    - destroy
