---
- name: Verify
  hosts: all
  vars:
    # https://github.com/cheretbe/notes/blob/master/ansible.md#environment-variables
    test_converge_ansible_user: "{{ lookup('env','MOLECULE_USER_NAME') | default('ansible-test', true) }}"
  tasks:

    - name: "Verify unattended upgrades settings"
      include_tasks: "../../../tests/helper_tasks/run_test_infra.yml"
      vars:
        test_dir: "{{ playbook_dir }}/../../tests"
