---
lint: |
  set -e
  ansible-lint

scenario:
  test_sequence:
    # - dependency
    - lint
    # - cleanup
    - destroy
    # - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    # - cleanup
    - destroy

verifier:
  name: testinfra
  directory: ../../tests/
  options:
    # These are actually pytest parameters (testinfra is a pytest plugin)
    v: true
    # k: dummy
    # s: true
