---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: centos-7
    image: pycontribs/centos:7
    pre_build_image: true
  - name: centos-8
    image: pycontribs/centos:8
    pre_build_image: true
  - name: ubuntu-bionic
    image: percygrunwald/docker-ubuntu1804-ansible:latest
    pre_build_image: true
  - name: ubuntu-xenial
    image: percygrunwald/docker-ubuntu1604-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
