---

lint: |
  set -e
  yamllint .
  ansible-lint
  #flake8
dependency:
  name: galaxy
driver:
  name: podman
  name: vagrant
platforms:
  - name: ubuntu-jammy
    box: ubuntu/jammy64

  - name: debian-12
    box: debian/bookworm64

  # - name: ubuntu-jammy
  #   image: docker.io/geerlingguy/docker-ubuntu2204-ansible
  #   pre_build_image: true
  #   command: /lib/systemd/systemd

  # - name: debian-11
  #   image: docker.io/geerlingguy/docker-debian11-ansible:latest
  #   pre_build_image: true
  #   command: /lib/systemd/systemd

  # - name: debian-12
  #   image: docker.io/geerlingguy/docker-debian12-ansible:latest
  #   pre_build_image: true
  #   command: /lib/systemd/systemd

provisioner:
  name: ansible
verifier:
  name: ansible
