---
# tasks file for linux-utils

- name: Install APT packages
  apt:
    name:
      - mc
      - htop
      - net-tools
      - dnsutils
      - mtr-tiny
      - ncdu
      - wget
      - git
      - nano
      - traceroute
      - colordiff
      - jq
      - pv
    update_cache: true
    cache_valid_time: "{{ '1d' | community.general.to_seconds | int }}"
    lock_timeout: "{{ '15m' | community.general.to_seconds | int }}"
  become: true
  when: ansible_os_family == "Debian"

- name: Make sure EPEL repo is enabled
  yum:
    name: epel-release
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: Install YUM packages
  yum:
    name:
      - mc
      - htop
      - net-tools
      - bind-utils
      - mtr
      - ncdu
      - wget
      - git
      - nano
      - traceroute
      - colordiff
      - jq
      - pv
    state: present
  become: true
  when: ansible_os_family == "RedHat"
