---
# tasks file for linux-utils

- name: Install APT packages
  ansible.builtin.apt:
    name:
      - mc
      - htop
      - net-tools
      - dnsutils
      - mtr-tiny
      - ncdu
      - wget
      - git
      - nano
      - traceroute
      - colordiff
      - jq
      - pv
    update_cache: true
    cache_valid_time: "{{ '1d' | community.general.to_seconds | int }}"
    lock_timeout: "{{ '15m' | community.general.to_seconds | int }}"
  become: true
  when: ansible_facts['os_family'] == "Debian"
