---
# tasks file for nagios-client

- name: Set common packages
  set_fact:
    nagios_client_apt_packages: [
      "git", "libconfig-json-perl", "nagios-nrpe-server", "python-tz",
      "python-dateutil", "python-lxml"
    ]

- name: Add packages specific to Ubuntu Bionic and Xenial
  set_fact:
    nagios_client_apt_packages: >
      {{ nagios_client_apt_packages + ['python', 'nagios-plugins', 'python-requests'] }}
  when: ansible_distribution_release == "bionic" or ansible_distribution_release == "xenial"

# TODO: add separate role for smartmontools (with custom config) and use it here
- name: Add smartmontools package when not running in a VM
  set_fact:
    nagios_client_apt_packages: >
      {{ nagios_client_apt_packages + ['smartmontools'] }}
  when: ansible_virtualization_role != "guest"

# - debug:
#     var: nagios_client_apt_packages

- include_role: name="../apt-wait-for-unlock"
  when: ansible_os_family == "Debian"

- name: Install prerequisite packages
  package: 
    name: "{{ nagios_client_apt_packages }}"
    state: present
  become: true

- name: Checkout custom plugins git repo
  git:
    repo: https://github.com/cheretbe/nagios-plugins.git
    dest: /var/lib/nagios/nagios-plugins
  become_user: nagios
  become: true

- name: "Add sudoers file to enable passwordless sudo commands for nagios user"
  template:
    src: etc_sudoers_d_nagios.j2
    dest: /etc/sudoers.d/ansible_nagios
    owner: root
    group: root
    mode: 0440
  become: true

- name: "Add custom NRPE settings template"
  template:
    src: etc_nagios_nrpe_d_ansible_custom_cfg.j2
    dest: /etc/nagios/nrpe.d/ansible_custom.cfg
    owner: root
    group: root
    mode: 0644
    # Don't replace file if it already exists
    force: no
  become: true

- name: Create log directory for update script
  file:
    path: /var/lib/nagios/log
    state: directory
    mode: 0755
    owner: nagios
    group: nagios
  become: true

- name: Add cron job for daily nagios-plugins repo update
  cron:
    name: Check for nagios-plugins repository updates daily
    # Using seed ensures random, but idempotent numbers
    minute: "{{ 23 | random(seed=inventory_hostname) }}"
    hour: "{{ 59 | random(seed=inventory_hostname) }}"
    user: nagios
    job: >
      /var/lib/nagios/nagios-plugins/update/update_nagios_plugins.sh >>
      /var/lib/nagios/log/nagios-plugins-update.log
    cron_file: nagios-plugins-update
  become: true

- name: "Add log rotation rule for update script log"
  template:
    src: etc_cron_d_nagios-plugins-update.j2
    dest: /etc/logrotate.d/nagios-plugins-update
    owner: root
    group: root
    mode: 0644
  become: true
