required_plugins = %w(vagrant-vbguest)

plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "This Vagrantfile needs one or more additional plugins to be installed: #{plugins_to_install.join(', ')}"
  puts "Use the following command:\n\n"
  puts "vagrant plugin install #{plugins_to_install.join(' ')}\n\n"
  abort "Installation of one or more additional plugins needed. Aborting."
end

Vagrant.configure("2") do |config|
  config.vm.define :ansible do |ansible|
    ansible.vm.box = "ubuntu/bionic64"
    ansible.vm.provider "virtualbox" do |vb|
      vb.memory = "6144"
      vb.cpus = "2"
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
      # prevent 'ubuntu-xenial-16.04-cloudimg-console.log' file creation
      # https://groups.google.com/forum/#!topic/vagrant-up/eZljy-bddoI
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]

      ansible.vm.synced_folder "./root_srv/salt", "/srv/salt"
      ansible.vm.synced_folder "../../../", "/ansible-playbooks"
    end
    ansible.vm.hostname = "ansible"
    ansible.vm.network "forwarded_port", guest: 80, host: 8080
    ansible.vm.network "private_network", ip: "172.24.0.10", virtualbox__intnet: "vagrant-intnet"

    ansible.vm.provision "shell", name: "python-pygit2 installation", keep_color: true,
      inline: "apt-get -y -q update && apt-get -y -q install python-pygit2"

    ansible.vm.provision :salt do |salt|
      salt.masterless = true
      salt.run_highstate = true
      salt.install_type = "stable"
    end

  #   ansible.vm.provision "shell", name: "Create symlink to current repo",
  #     keep_color: true,
  #     inline: <<-SHELL
  #       mkdir -p /usr/share/ansible
  #       ln -sfn /ansible-playbooks /usr/share/ansible/roles
  #     SHELL
  end

  config.vm.define :"ubuntu-bionic", autostart: false do |ubuntu_bionic|
    ubuntu_bionic.vm.box = "ubuntu/bionic64"
    ubuntu_bionic.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
      # prevent 'ubuntu-xenial-16.04-cloudimg-console.log' file creation
      # https://groups.google.com/forum/#!topic/vagrant-up/eZljy-bddoI
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end
    ubuntu_bionic.vm.synced_folder "./root_srv/salt", "/srv/salt"
    ubuntu_bionic.vm.hostname = "ubuntu-bionic"
    ubuntu_bionic.vm.network "private_network", ip: "172.24.0.11", virtualbox__intnet: "vagrant-intnet"

    ubuntu_bionic.vm.provision :salt do |salt|
      salt.masterless = true
      salt.run_highstate = true
      salt.install_type = "stable"
    end
  end

  config.vm.define :"ubuntu-xenial", autostart: false do |ubuntu_xenial|
    ubuntu_xenial.vm.box = "ubuntu/xenial64"
    ubuntu_xenial.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
      # prevent 'ubuntu-xenial-16.04-cloudimg-console.log' file creation
      # https://groups.google.com/forum/#!topic/vagrant-up/eZljy-bddoI
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end
    ubuntu_xenial.vm.synced_folder "./root_srv/salt", "/srv/salt"
    ubuntu_xenial.vm.hostname = "ubuntu-xenial"
    ubuntu_xenial.vm.network "private_network", ip: "172.24.0.12", virtualbox__intnet: "vagrant-intnet"

    ubuntu_xenial.vm.provision :salt do |salt|
      salt.masterless = true
      salt.run_highstate = true
      salt.install_type = "stable"
    end
  end

  config.vm.define :"centos-7", autostart: false do |centos_7|
    centos_7.vm.box = "centos/7"
    centos_7.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    end

    centos_7.vbguest.auto_update = true

    centos_7.vm.synced_folder "./root_srv/salt", "/srv/salt"
    centos_7.vm.hostname = "centos-7"
    centos_7.vm.network "private_network", ip: "172.24.0.13", virtualbox__intnet: "vagrant-intnet"

    centos_7.vm.provision :salt do |salt|
      salt.masterless = true
      salt.run_highstate = true
      salt.install_type = "stable"
    end
  end

  config.vm.define :win7, autostart: false do |win7|
    win7.vm.box = "cheretbe/win7_ru_64"
    win7.winrm.username = "vagrant"
    win7.winrm.password = "#{ENV['AO_DEFAULT_VAGRANT_PASSWORD']}"
    win7.vm.boot_timeout = 600
    win7.vm.hostname = "win7"
    win7.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end
    win7.vm.network "private_network", ip: "172.24.0.14", virtualbox__intnet: "vagrant-intnet"
    # win7.vm.provision "shell", path: "provision-script.ps1"
  end

end