---

- name: Restart OpenVPN client service
  ansible.builtin.systemd:
    name: "openvpn-client@{{ ovpn_client_server_type }}.service"
    state: restarted
  become: yes

- name: Run daemon-reload for systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes
