---
# tasks file for linux-unattended-upgrades

- name: Setup unattended upgrades (Ubuntu)
  include_tasks: unattended_upgrades_ubuntu.yml
  when: ansible_os_family == "Debian"

- name: Setup unattended upgrades (CentOS)
  include_tasks: unattended_upgrades_centos.yml
  when: ansible_os_family == "RedHat"
