---
- name: Install apt 'unattended-upgrades' package
  apt:
    name: unattended-upgrades
    update_cache: true
    cache_valid_time: "{{ '1d' | community.general.to_seconds | int }}"
    lock_timeout: "{{ '15m' | community.general.to_seconds | int }}"
  become: true

- name: Create custom unattended upgrades configuration file
  template:
    src: etc_apt_apt.conf.d_90-ansible-unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/90-ansible-unattended-upgrades
    owner: root
    group: root
    mode: 0644
  become: true
