---
- name: Converge and verify
  hosts: ubuntu-bionic, ubuntu-focal
  vars:
    # https://github.com/cheretbe/notes/blob/master/ansible.md#environment-variables
    ansible_user: "{{ lookup('env','MOLECULE_USER_NAME') | default('ansible-test', true) }}"

  tasks:
    # ==========================================================================
    - name: "Install backuppc-server version 4.3.2"
      include_role:
        name: "backuppc-server"
      # vars:
      #   backuppc_server_version: "4.3.2"
      #   backuppc_server_rsync_bpc_version: "3.0.9.15"
      #   backuppc_server_backuppc_xs_version: "0.59"

    - name: "Verify version 4.3.2 installation"
      include_tasks: "../../../tests/helper_tasks/run_test_infra.yml"
      vars:
        test_dir: "{{ playbook_dir }}/../../tests"
        test_extra_params: "--backuppc-version=4.3.2 --backuppc-xs-version=0.59 --rsync-bpc-version=3.0.9.15"

    # ==========================================================================
    # - name: "Install backuppc-server (latest)"
    #   include_role:
    #     name: "backuppc-server"

    # - name: "Verify data directory settings"
    #   include_tasks: "../../../tests/helper_tasks/run_test_infra.yml"
    #   vars:
    #     test_dir: "{{ playbook_dir }}/../../tests"
