---
# tasks file for linux-locale

- name: Generate locales using locale_gen
  community.general.locale_gen:
    name: "{{ item.language_country }}.{{ item.encoding }}"
    state: present
  become: true
  loop: "{{ linux_locale_locales_to_generate }}"
  when: ansible_facts['os_family'] == "Debian"

- name: "Set system locale config"
  ansible.builtin.template:
    src: "locale.conf.j2"
    dest: /etc/default/locale
    mode: "0644"
    backup: true
  become: true
