---
- name: Converge
  hosts: all
  vars:
    ansible_user: ansible

  tasks:
    - name: Set Zabbix version fact
      set_fact:
        zabbix_repo_version: "{{ lookup('env','TEST_ZABBIX_VERSION') }}"
      # [602] Don't compare to empty string
      # Not sure what to use instead
      # https://github.com/ansible/ansible-lint/issues/457
      when: lookup('env','TEST_ZABBIX_VERSION') != '' # noqa602

    - name: "Include zabbix-repo"
      include_role:
        name: "zabbix-repo"
    - name: "Include zabbix-server"
      include_role:
        name: "zabbix-server"
