---

- name: Provision ansible user
  hosts: "{{ ansible_limit | default(omit) }}"
  tasks:

    - name: Create ansible user
      ansible.builtin.user:
        groups: [sudo]
        name: ansible-user
      become: true

    - name: Add authorized key for ansible user
      ansible.posix.authorized_key:
        user: ansible-user
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPVefeo0N6xgNLQGPFm66EgauPJ8esnuj2Pi7IPb866IgRazKBRZCk35KlbaN0Tzzf9zTFuY4BB4F3kFYh9pIRa6fX6yHU9yUo5kcjqVTeTKXzHkt4e9qOIoXr9JSpZTCIURLUO70lpfeeiVo1xdBCT5ODI04btVHIt1DygwfZd68AjASSXrIkrrsN10qeBaLi9Jwxl+E++53hV558PkZIkqe5aph7BzUG+F2nxWJMftpIhKD7hAtztAvelNd1Nw+mmnubUQTICM6xGv3Y8Ucb51NqO14x89tYVZBpSH518ASTcl4fh7OhW6JZraR/PfzCuZto9nTCVhAsQVX/jblL ansible-user"
        state: present
      become: true

    - name: Sudo without password for ansible user
      ansible.builtin.copy:
        content: '%sudo ALL=(ALL:ALL) NOPASSWD:ALL'
        dest: /etc/sudoers.d/ansible_user
        mode: 0440
      become: true
