---

lint: |
    set -e
    ansible-lint --exclude molecule/

verifier:
  name: testinfra
  directory: ../../tests/
  options:
    v: true
    # s: true
    user-name: test-user
    ssh-public-key-file=${MOLECULE_PROJECT_DIRECTORY}/molecule/common/test.key.pub: true
    use-test-sudo-entries: true

scenario:
  test_sequence:
    # - dependency
    - lint
    # - cleanup
    - destroy
    # - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    # - cleanup
    - destroy
