---
# tasks file for zabbix-repo

- name: Check distribution
  fail:
    msg: "Only Ubuntu 18.04 and 16.04 are supported at the moment"
  when: not (ansible_distribution == "Ubuntu" and (ansible_distribution_release == "bionic" or ansible_distribution_release == "xenial"))

- name: Add Zabbix repository key
  apt_key:
    url: http://repo.zabbix.com/zabbix-official-repo.key
    state: present

- name: Add Zabbix repository
  apt_repository:
    repo: deb http://repo.zabbix.com/zabbix/{{ zabbix_repo_version }}/ubuntu {{ ansible_distribution_release }} main
    state: present

- name: Add Zabbix repository (sources)
  apt_repository:
    repo: deb-src http://repo.zabbix.com/zabbix/{{ zabbix_repo_version }}/ubuntu {{ ansible_distribution_release }} main
    state: present

- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: "yes"
    update_cache: yes
    # Fix for warning message "Could not find aptitude. Using apt-get instead"
    force_apt_get: yes
