---
# tasks file for zabbix-repo

- name: Update and upgrade apt packages
  apt:
    upgrade: "yes"
    update_cache: yes
    # Fix for warning message "Could not find aptitude. Using apt-get instead"
    force_apt_get: yes
  become: true

# Convert repo version variable to a fact, so that other roles could use it
- name: Set Zabbix version fact
  set_fact:
    zabbix_repo_version: "{{ zabbix_repo_version }}"

- name: Install gpg-agent package
  apt:
    name:  ["gpg-agent"]
    # Fix for warning message "Could not find aptitude. Using apt-get instead"
    force_apt_get: yes
    update_cache: no
  become: true

- name: Add Zabbix repository key
  apt_key:
    url: http://repo.zabbix.com/zabbix-official-repo.key
    state: present
  become: true

- name: Add Zabbix repository
  apt_repository:
    repo: deb http://repo.zabbix.com/zabbix/{{ zabbix_repo_version }}/ubuntu {{ ansible_distribution_release }} main
    state: present
  become: true

- name: Add Zabbix repository (sources)
  apt_repository:
    repo: deb-src http://repo.zabbix.com/zabbix/{{ zabbix_repo_version }}/ubuntu {{ ansible_distribution_release }} main
    state: present
  become: true

- name: Update apt package list
  apt:
    update_cache: yes
    # Fix for warning message "Could not find aptitude. Using apt-get instead"
    force_apt_get: yes
  become: true