---
# tasks file for burp-repo

- name: Check distribution
  fail:
    msg: "Only Ubuntu 18.04 and 16.04 are supported at the moment"
  when: not (ansible_distribution == "Ubuntu" and (ansible_distribution_release == "bionic" or ansible_distribution_release == "xenial"))

- name: Add Ziirish repository key
  apt_key:
    url: http://ziirish.info/repos/ubuntu.gpg
    state: present
  become: yes

- name: Add Ziirish repository
  apt_repository:
    repo: deb http://ziirish.info/repos/ubuntu/{{ ansible_distribution_release }} zi-stable main
    state: present
  become: yes

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    # 1 hour
    cache_valid_time: 3600
  become: yes
