---
- name: Set user name
  set_fact:
    win_settings_user_name: "{{ win_settings_user_name | default(ansible_user) }}"

- name: Get (or create) user profile
  community.windows.win_user_profile:
    username: "{{ win_settings_user_name }}"
    state: present
  register: win_settings_user_profile

- name: Make sure Total Commander settings directory exists
  ansible.windows.win_file:
    path: "{{ win_settings_user_profile.path }}\\AppData\\Roaming\\GHISLER"
    state: directory

- name: Get Total Commander settings info
  ansible.windows.win_stat:
    path: "{{ win_settings_user_profile.path }}\\AppData\\Roaming\\GHISLER\\wincmd.ini"
  register: win_settings_wincmd_ini

# Do not overwrite existing file
- name: Copy Total Commander settings
  ansible.windows.win_template:
    src: wincmd.ini
    dest: "{{ win_settings_user_profile.path }}\\AppData\\Roaming\\GHISLER\\wincmd.ini"
  when: not win_settings_wincmd_ini.stat.exists
