---

- name: Check if mandatory variables are defined
  assert:
    that:
      - ovpn_server_ca_cert is defined
      - ovpn_server_cert is defined
      - ovpn_server_key is defined
      - ovpn_server_dns_name is defined

- name: Install apt packages
  apt:
    name: |
      {{ ['openvpn'] + (['bind9', 'bind9utils'] if (ovpn_server_dns_resolver|bool) else []) }}
    update_cache: yes
    cache_valid_time: "{{ '1d' | community.general.to_seconds | int }}"
    lock_timeout: "{{ '15m' | community.general.to_seconds | int }}"
  become: yes

- name: Create server config directory structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  become: yes
  loop:
    - "/etc/openvpn/server"
    - "/etc/openvpn/server/client-config"

- name: Copy server cryptographic files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/etc/openvpn/server/{{ item.dest }}"
    mode: "{{ item.mode }}"
  become: yes
  loop:
    - {"src": "{{ ovpn_server_ca_cert }}", "dest": "ca.crt", mode: "0644"}
    - {"src": "{{ ovpn_server_cert }}", "dest": "server.crt", mode: "0644"}
    - {"src": "{{ ovpn_server_key }}", "dest": "server.key", mode: "0600"}

- name: Generate HMAC key
  ansible.builtin.command: /usr/sbin/openvpn --genkey --secret /etc/openvpn/server/ta.key
  args:
    creates: /etc/openvpn/server/ta.key

- name: Set HMAC key permissions
  ansible.builtin.file:
    path: /etc/openvpn/server/ta.key
    mode: '0644'

- name: Create OpenVPN server config
  ansible.builtin.template:
    src: server.conf.j2
    dest: "/etc/openvpn/server/server.conf"
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Restart 'openvpn-server@server' service

- name: Enable and start 'openvpn-server@server' service
  ansible.builtin.systemd:
    name: openvpn-server@server.service
    state: started
    enabled: yes
  become: yes

- name: Create OpenVPN client config base file
  ansible.builtin.template:
    src: client_base.conf.j2
    dest: /etc/openvpn/server/client-config/client_base.conf
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Copy client config creation script
  ansible.builtin.copy:
    src: make_client_config.sh
    dest: /etc/openvpn/server/client-config/make_client_config.sh
    mode: '0755'
  become: yes

- name: Configure bind9
  block:
    - name: Make sure systemd-resolved DNS stub is disabled
      include_role: name="{{ role_path }}/../linux-dns"

    - name: Create bind9 options file
      ansible.builtin.template:
        src: etc_bind_named.conf.options.j2
        dest: /etc/bind/named.conf.options
        owner: root
        group: root
        mode: '0644'
        backup: yes
      become: yes
      notify: Restart 'named' service

    - name: Create bind9 service startup options file
      ansible.builtin.template:
        src: etc_default_named.j2
        dest: /etc/default/named
        owner: root
        group: root
        mode: '0644'
        backup: yes
      become: yes
      notify: Restart 'named' service

    # - name: Create bind9 log directory
    #   ansible.builtin.file:
    #     path: /var/log/named
    #     state: directory
    #     owner: bind
    #     group: bind

    - name: Enable and start 'named' service
      ansible.builtin.systemd:
        name: named
        state: started
        enabled: yes
      become: yes

  when: ovpn_server_dns_resolver|bool
